var providers = [];
var module = require('../module/module.client');
providers.push(module.Module);
var module_client_1 = require('../module/module.client');
exports.Module = module_client_1.Module;
var module2 = require('../module2/module2.client');
providers.push(module2.Module2);
var module2_client_1 = require('../module2/module2.client');
exports.Module2 = module2_client_1.Module2;
exports.Providers = providers;
